export const HARDCODED_ACCOUNT_MAP: Record<string, string> = {
  "wa government-health": "Joanne Ballantyne",
  "westrac": "Benjamin Mackie",
  "mineral resources limited": "Joshua Mostratos",
  "wa government-shared services": "Joanne Ballantyne",
  "wa government-energy": "Joanne Ballantyne",
  "wa government-transport": "Joanne Ballantyne",
  "wa newspapers": "Rienzie Delilkan",
  "metso": "Rienzie Delilkan",
  "c j d equipment pty ltd": "Joshua Mostratos",
  "gold corporation": "Joshua Mostratos",
  "itech world pty ltd": "Rienzie Delilkan",
  "powerlines plus pty ltd": "Joshua Mostratos",
  "syrnecut": "Benjamin Mackie",
  "wa government-council": "Joanne Ballantyne",
  "fluid connectors (wa) pty ltd": "Rienzie Delilkan",
  "force technology": "Rienzie Delilkan",
  "wurth australia pty ltd": "Joshua Mostratos",
  "dyno nobel": "Rienzie Delilkan",
  "intertek robotic laboratories pty ltd": "Joshua Mostratos",
  "horizon gold limited": "Joshua Mostratos",
  "ausdrill": "Joshua Mostratos",
  "bmeco international pty ltd": "Rienzie Delilkan",
  "coates hire": "Rienzie Delilkan",
  "national auto glass supplies (australia) pty ltd": "Rienzie Delilkan",
  "the trustee for dcs australia unit trust": "Joshua Mostratos",
  "wa government-education": "Joanne Ballantyne",
  "holcim (australia) pty ltd": "Joshua Mostratos",
  "intertek testing services (australia) pty. ltd. (pa)": "Joshua Mostratos",
  "afgri equipment": "Rienzie Delilkan",
  "marcem australia pty ltd": "Rienzie Delilkan",
  "japanese truck & bus spares pty ltd": "Joshua Mostratos",
  "decml australia": "Joshua Mostratos",
  "milner's pty ltd": "Joshua Mostratos",
  "truck centre (wa) pty ltd": "Joshua Mostratos",
  "macmahon": "Joshua Mostratos",
  "wa government-legal": "Joanne Ballantyne",
  "mlg oz pty ltd": "Joshua Mostratos",
  "fred group pty ltd": "Joshua Mostratos",
  "nrw pty ltd": "Rienzie Delilkan",
  "onslow freight & logistics": "Joshua Mostratos",
  "united fuel injection": "Joshua Mostratos",
  "monadelphous engineering": "Joshua Mostratos",
  "sea to summit pty ltd": "Joshua Mostratos",
  "ddh1": "Joshua Mostratos",
  "funky monkey bars pty ltd": "Rienzie Delilkan",
  "alcolizer pty ltd": "Rienzie Delilkan",
  "bgc australia": "Rienzie Delilkan",
  "urika transport agent": "Rienzie Delilkan",
  "dorsett retail pty ltd": "Joshua Mostratos",
  "high energy": "Joshua Mostratos",
  "sunlec international pty ltd": "Joshua Mostratos",
  "btp": "Joshua Mostratos",
  "webb & waltman pty ltd": "Rienzie Delilkan",
  "petro-ject pty ltd": "Joshua Mostratos",
  "golding": "Rienzie Delilkan",
  "growplay": "Joshua Mostratos",
  "rcr mining": "Rienzie Delilkan",
  "manjimup freight": "Rienzie Delilkan",
  "ranger exploration drilling pty ltd": "Joshua Mostratos",
  "stp parts pty ltd": "Joshua Mostratos",
  "radlink communications": "Rienzie Delilkan",
  "lowo transport": "Rienzie Delilkan",
  "midwest medical dispensary": "Rienzie Delilkan",
  "ramsey bros. pty. ltd.": "Rienzie Delilkan",
  "iron mine services pty ltd": "Joshua Mostratos",
  "lt nguyen & the trustee for van thang vo & le t": "Namra Khan",
  "moot drinks co": "Namra Khan",
  "lincom wa pty ltd": "Rienzie Delilkan",
  "alltype engineering pty ltd": "Joshua Mostratos",
  "access equipment hire australia pl": "Joshua Mostratos",
  "rg transport wa": "Rienzie Delilkan",
  "alsco": "Rienzie Delilkan",
  "woodside energy ltd.": "Benjamin Mackie",
  "action drill & blast pty ltd": "Joshua Mostratos",
  "d'orsogna ltd": "Rienzie Delilkan",
  "mcintosh & son": "Rienzie Delilkan",
  "mondino pty ltd": "Joshua Mostratos",
  "a. richards": "Joshua Mostratos",
  "diab engineering pty ltd": "Rienzie Delilkan",
  "onslow iron pty ltd": "Joshua Mostratos",
  "wa government": "Joanne Ballantyne",
  "logistics management group": "Joshua Mostratos",
  "minres marine": "Joshua Mostratos",
  "vega resources": "Joshua Mostratos",
  "party source pty ltd": "Rienzie Delilkan",
  "leicester meaghan erica": "Isaac De Pina",
  "wa government-dts transport": "Joanne Ballantyne",
  "hobbytech international pty ltd": "Namra Khan",
  "flex fitness equipment": "Rienzie Delilkan",
  "downrange services": "Namra Khan",
  "norgent australia": "Joshua Mostratos",
  "wa government-fair work commission (parcel": "Joanne Ballantyne",
  "pacific health care": "Namra Khan",
  "wa government-justice": "Joanne Ballantyne",
  "ecobom": "Namra Khan",
  "hellers australia": "Namra Khan",
  "radiant lighting pty ltd": "Namra Khan",
  "jacks winches": "Joshua Mostratos",
  "elegantia": "Namra Khan",
  "onslow infraco": "Joshua Mostratos",
  "quickpack holdings": "Joshua Mostratos",
  "solutions it": "Namra Khan",
  "cd ceramics": "Namra Khan",
  "sls scientific": "Joshua Mostratos",
  "vine signs pty ltd": "Namra Khan",
  "faxton frank rex": "Isaac De Pina",
  "harvestaire": "Joshua Mostratos",
  "pindan beef company": "Namra Khan",
  "energy resources limited": "Joshua Mostratos",
  "perth bullion": "Joshua Mostratos",
  "concept audio visual nsw trust": "Isaac De Pina",
  "s. new business - committed-isaac de pina": "Isaac De Pina",
  "s. new business - committed-namra khan": "Namra Khan",
  "aircraft maintenance specialists": "Namra Khan",
  "fuib group pty ltd": "Benjamin Mackie",
  "chrisco hampers australia limited": "Joshua Mostratos",
  "dna aerospace pty ltd": "Namra Khan",
  "hydraulic & pneumatic pty ltd": "Namra Khan",
  "leinster contracting services": "Rienzie Delilkan",
  "shaving essentials pty. ltd.": "Namra Khan",
  "wa government-dts": "Joanne Ballantyne"
};
