"use client";

import { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useCollection, useFirestore, useMemoFirebase, useDoc } from '@/firebase';
import { collection, query, where, doc } from 'firebase/firestore';
import { FileText, Send, Loader2, Sparkles, Presentation, Target, TargetIcon, Users, CheckSquare } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { getCurrentWeek } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { generateAiReport, AiReportOutput } from '@/ai/flows/generate-ai-report';
import { jsPDF } from "jspdf";
import { playbooks as defaultPlaybooks } from './territory-playbook';
import { useAuth } from '@/contexts/auth-context';

export function AiReportGenerator() {
  const db = useFirestore();
  const { toast } = useToast();
  const { profile } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [report, setReport] = useState<AiReportOutput | null>(null);
  const currentWeek = getCurrentWeek();

  // Fetch Group 90 Day Plan
  const groupPlanRef = useMemoFirebase(() => {
    if (!db || !profile?.uid) return null;
    return doc(db, 'onboardingProgress', `${profile.uid}_GROUP_90`);
  }, [db, profile?.uid]);
  const { data: groupPlanDoc } = useDoc(groupPlanRef);

  // Fetch Pipeline Data
  const pipelineQuery = useMemoFirebase(() => {
    if (!db) return null;
    return query(collection(db, 'pipelineReviews'), where('week', '==', currentWeek));
  }, [db, currentWeek]);
  const { data: teamPipeline } = useCollection(pipelineQuery);

  // Fetch Playbook Config (fallback to default)
  const configRef = useMemoFirebase(() => db ? doc(db, 'strategyConfig', 'territoryPlaybooks') : null, [db]);
  const { data: playbookConfig } = useDoc(configRef);

  const runGeneration = async () => {
    if (!db || !teamPipeline) {
      toast({ variant: "destructive", title: "Data Loading", description: "Still loading team data, please wait..." });
      return;
    }
    
    setIsGenerating(true);

    try {
      // 1. Prepare 90 Day Plan
      const tasksObj = groupPlanDoc?.tasks || {};
      const planArray = Object.keys(tasksObj).map(key => ({
        task: key,
        completed: !!tasksObj[key]
      }));

      // 2. Prepare Pipeline
      const pipelineArray = teamPipeline.map(p => ({
        bdmName: p.userName || 'Unknown BDM',
        opportunityName: p.opportunityName || p.pipeline || 'Unnamed Opp',
        stage: p.stage || 'Discovery',
        value: Number(p.value) || 0
      }));

      // 3. Prepare Playbooks
      const activePlaybooks = playbookConfig?.data || defaultPlaybooks;

      const result = await generateAiReport({
        week: currentWeek,
        group90DayPlan: planArray,
        teamPipeline: pipelineArray,
        playbooks: activePlaybooks
      });

      setReport(result);
      toast({ title: "Presentation Ready", description: "AI Presentation Report has been generated." });
    } catch (error) {
      console.error("AI Generation failed", error);
      toast({ variant: "destructive", title: "Generation Failed", description: "Could not synthesize presentation report." });
    } finally {
      setIsGenerating(false);
    }
  };

  const exportToPdf = () => {
    if (!report) return;
    setIsExporting(true);
    try {
      const doc = new jsPDF();
      const margin = 20;
      let y = 20;

      // Title Slide
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      const titleLines = doc.splitTextToSize(report.presentationTitle.toUpperCase(), 170);
      doc.text(titleLines, margin, y);
      y += (titleLines.length * 10) + 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Week: ${currentWeek} • Generated by AI`, margin, y);
      y += 15;
      doc.setDrawColor(0);
      doc.line(margin, y, 190, y);
      y += 15;

      const addSection = (title: string, content: string) => {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(title.toUpperCase(), margin, y);
        y += 7;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(content, 170);
        doc.text(lines, margin, y);
        y += (lines.length * 5) + 12;
      };

      addSection("Group 90-Day Plan Review", report.groupPlanReview);
      addSection("Pipeline & Opportunities", report.userOpportunities);
      addSection("Strategy Playbooks Execution", report.strategyPlaybooks);
      addSection("Executive Key Takeaways", report.keyTakeaways);
      
      doc.save(`Presentation_Report_${currentWeek}.pdf`);
      toast({ title: "PDF Exported", description: "Presentation saved to local storage." });
    } catch (e) {
      toast({ variant: "destructive", title: "Export Failed" });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card className="border-none shadow-2xl bg-white overflow-hidden">
      <CardHeader className="bg-slate-900 text-white pb-6 pt-6">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <CardTitle className="text-xl flex items-center gap-2 font-black tracking-tight uppercase">
              <Presentation className="w-5 h-5 text-accent" />
              AI Presentation Report
            </CardTitle>
            <CardDescription className="text-slate-400 font-bold uppercase text-[10px] tracking-widest">
              Synthesize 90-Day Plans, Playbooks, and Pipeline for Senior Managers
            </CardDescription>
          </div>
          <Badge className="bg-white/10 text-white border-none uppercase tracking-widest text-[10px] font-black hover:bg-white/20 transition-colors">Week {currentWeek.split('-')[1]}</Badge>
        </div>
      </CardHeader>
      
      <CardContent className="p-0">
        {!report && !isGenerating ? (
          <div className="text-center py-24 px-6">
            <div className="w-20 h-20 bg-accent/10 rounded-full flex items-center justify-center mx-auto mb-6">
              <Sparkles className="w-10 h-10 text-accent" />
            </div>
            <h3 className="text-lg font-black text-primary mb-2 uppercase tracking-tight">Generate Weekly Presentation</h3>
            <p className="text-sm text-muted-foreground font-medium max-w-md mx-auto mb-8">
              Click below to aggregate the team's 90-day plan progress, pipeline metrics, and territory playbooks into a polished presentation format.
            </p>
            <Button className="bg-accent hover:bg-accent/90 text-white font-black h-14 px-10 rounded-xl text-sm shadow-xl shadow-accent/20 uppercase tracking-widest transition-all hover:scale-105" onClick={runGeneration}>
              <Sparkles className="w-4 h-4 mr-2" /> Generate AI Report
            </Button>
          </div>
        ) : isGenerating ? (
          <div className="flex flex-col items-center justify-center py-32 space-y-6 bg-slate-50">
            <div className="relative">
              <div className="absolute inset-0 bg-accent/20 rounded-full blur-xl animate-pulse" />
              <Loader2 className="w-12 h-12 animate-spin text-accent relative z-10" />
            </div>
            <div className="space-y-1 text-center">
              <p className="text-sm font-black text-primary uppercase tracking-widest animate-pulse">Consulting the Oracle...</p>
              <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest">Cross-referencing Playbooks & Pipeline Data</p>
            </div>
          </div>
        ) : report ? (
          <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700 bg-slate-50">
            <div className="flex items-center justify-between border-b pb-4">
               <h2 className="text-2xl font-black text-primary uppercase tracking-tight max-w-2xl">{report.presentationTitle}</h2>
               <Button variant="outline" className="border-primary/20 font-black h-10 px-6 rounded-lg bg-white shadow-sm uppercase text-[10px] tracking-widest" onClick={exportToPdf} disabled={isExporting}>
                 {isExporting ? <Loader2 className="animate-spin w-4 h-4 mr-2" /> : <FileText className="w-4 h-4 mr-2" />} Export PDF
               </Button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {/* Group 90 Day Plan */}
              <div className="space-y-3 bg-white p-6 rounded-2xl border shadow-sm relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity"><CheckSquare className="w-24 h-24 text-blue-500" /></div>
                <h3 className="text-xs font-black text-blue-600 uppercase tracking-widest flex items-center gap-2">
                  <CheckSquare className="w-4 h-4" /> Group 90-Day Plan Review
                </h3>
                <p className="text-sm text-slate-700 font-medium leading-relaxed relative z-10 whitespace-pre-wrap">{report.groupPlanReview}</p>
              </div>

              {/* Pipeline & Opportunities */}
              <div className="space-y-3 bg-white p-6 rounded-2xl border shadow-sm relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity"><TargetIcon className="w-24 h-24 text-accent" /></div>
                <h3 className="text-xs font-black text-accent uppercase tracking-widest flex items-center gap-2">
                  <TargetIcon className="w-4 h-4" /> Pipeline & Opportunities
                </h3>
                <p className="text-sm text-slate-700 font-medium leading-relaxed relative z-10 whitespace-pre-wrap">{report.userOpportunities}</p>
              </div>

              {/* Playbooks */}
              <div className="space-y-3 bg-white p-6 rounded-2xl border shadow-sm relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity"><Target className="w-24 h-24 text-emerald-500" /></div>
                <h3 className="text-xs font-black text-emerald-600 uppercase tracking-widest flex items-center gap-2">
                  <Target className="w-4 h-4" /> Strategy Playbooks Alignment
                </h3>
                <p className="text-sm text-slate-700 font-medium leading-relaxed relative z-10 whitespace-pre-wrap">{report.strategyPlaybooks}</p>
              </div>

              {/* Key Takeaways */}
              <div className="space-y-3 bg-slate-900 p-6 rounded-2xl border-none shadow-xl relative overflow-hidden group text-white">
                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity"><Sparkles className="w-24 h-24 text-accent" /></div>
                <h3 className="text-xs font-black text-accent uppercase tracking-widest flex items-center gap-2">
                  <Sparkles className="w-4 h-4" /> Executive Takeaways
                </h3>
                <p className="text-sm text-slate-200 font-bold leading-relaxed relative z-10 whitespace-pre-wrap">{report.keyTakeaways}</p>
              </div>
            </div>

            <div className="pt-4 flex justify-center">
               <Button variant="ghost" onClick={() => setReport(null)} className="text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-primary">
                 Start Over / Regenerate
               </Button>
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
